### ISSUE TITLE
how to preprocess data for dpe?

### ISSUE THREAD

**Issue by ZhenYangIACAS** [xlhex/dpe#1]
Some examples are expected.

**Comment by xlhex** [comment]
I provide detailed data preprocessing steps in the readme file. Please have a look. If you still have any questions, feel free to contact me again.

**Comment by mzeidhassan** [comment]
Hi @xlhex 

First, thanks for making this available.

I think the ReadMe is not clear enough for some of us. For example, if I want to use this for translation. Do I need to train first? Or should I use the segment command only? The instructions under https://github.com/xlhex/dpe#machine-translation makes me think that only segmentation is required if I want to use this in translation.

I assume in this command "sh run_batch SRC TGT SEED":

SRC should be the source file and TGT should be the target/translation file. Am I right? Should this be parallel text files? 

Thanks in advance for your support.

**Comment by xlhex** [comment]
hi @mzeidhassan you're correct, to segment your corpus, you need to train a new segmentor first by following https://github.com/xlhex/dpe#training. then segment your corpus by using https://github.com/xlhex/dpe#map-inference

**Comment by xlhex** [comment]
addressed
